package constants

const CONST_SMTP_SERVER_HOST = "SMTP_SERVER_HOST"
const CONST_SMTP_SERVER_PORT = "SMTP_SERVER_PORT"
const CONST_SMTP_SERVER_USERNAME = "SMTP_SERVER_USERNAME"
const CONST_SMTP_SERVER_PASSWORD = "SMTP_SERVER_PASSWORD"

const BASIC_MAILER_FROM = "no-reply@test.com"
