package constants

const KEY_JWT_SIGN_UP_EMAIL_SECRET_KEY = "JWT_SIGN_UP_EMAIL_SECRET_KEY"
const KEY_JWT_SIGN_UP_EMAIL_AUDIENCE = "JWT_SIGN_UP_EMAIL_AUDIENCE"

const KEY_LANGUAGE = "Content-Language"

const KEY_BACKEND_HOST = "BACKEND_HOST"
const KEY_BACKEND_PORT = "BACKEND_PORT"
const KEY_BACKEND_SCHEME = "BACKEND_SCHEME"