// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
)

type CountryCode struct {
	CountryCode string         `json:"country_code"`
	Country     string         `json:"country"`
	Continent   sql.NullString `json:"continent"`
}

type Credential struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Email struct {
	ID               int64          `json:"id"`
	Address          sql.NullString `json:"address"`
	EmailConfirmedAt sql.NullTime   `json:"email_confirmed_at"`
	IsEmailConfirmed sql.NullBool   `json:"is_email_confirmed"`
}

type LinkedIn struct {
	ID                  int64          `json:"id"`
	Login               sql.NullString `json:"login"`
	LinkedInConfirmedAt sql.NullTime   `json:"linked_in_confirmed_at"`
	IsLinkedInConfirmed sql.NullBool   `json:"is_linked_in_confirmed"`
}

type Permission struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type Phone struct {
	ID               int64        `json:"id"`
	CountryCode      string       `json:"country_code"`
	Number           string       `json:"number"`
	PhoneConfirmedAt sql.NullTime `json:"phone_confirmed_at"`
	IsPhoneConfirmed sql.NullBool `json:"is_phone_confirmed"`
}

type Role struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type RoleAndPermission struct {
	RoleID       sql.NullInt64 `json:"role_id"`
	PermissionID sql.NullInt64 `json:"permission_id"`
}

type User struct {
	ID           int64          `json:"id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	AvatarUri    sql.NullString `json:"avatar_uri"`
	CredentialID sql.NullInt64  `json:"credential_id"`
	EmailID      sql.NullInt64  `json:"email_id"`
	PhoneID      sql.NullInt64  `json:"phone_id"`
	LinkedInID   sql.NullInt64  `json:"linked_in_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	IsConfirmed  sql.NullBool   `json:"is_confirmed"`
	RoleID       sql.NullInt64  `json:"role_id"`
}
