// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CredentialCreateOne(ctx context.Context, arg CredentialCreateOneParams) (Credential, error)
	CredentialGetById(ctx context.Context, id int64) (Credential, error)
	CredentialGetByUsername(ctx context.Context, username string) (Credential, error)
	CredentialResetPasswordById(ctx context.Context, arg CredentialResetPasswordByIdParams) (Credential, error)
	CredentialResetPasswordByUsername(ctx context.Context, arg CredentialResetPasswordByUsernameParams) (Credential, error)
	EmailConfirmByAddress(ctx context.Context, address sql.NullString) (Email, error)
	EmailConfirmById(ctx context.Context, id int64) (Email, error)
	EmailCreateConfirmedOne(ctx context.Context, arg EmailCreateConfirmedOneParams) (Email, error)
	EmailCreateOne(ctx context.Context, address sql.NullString) (Email, error)
	EmailDeleteByAddress(ctx context.Context, id int64) (Email, error)
	EmailDeleteById(ctx context.Context, id int64) (Email, error)
	LinkedInConfirmById(ctx context.Context, arg LinkedInConfirmByIdParams) (LinkedIn, error)
	LinkedInConfirmByLogin(ctx context.Context, arg LinkedInConfirmByLoginParams) (LinkedIn, error)
	LinkedInCreateOne(ctx context.Context, arg LinkedInCreateOneParams) (LinkedIn, error)
	LinkedInDeleteById(ctx context.Context, id int64) (LinkedIn, error)
	LinkedInDeleteByLogin(ctx context.Context, login sql.NullString) (LinkedIn, error)
	LinkedInGetById(ctx context.Context, id int64) (LinkedIn, error)
	PhoneConfirmById(ctx context.Context, arg PhoneConfirmByIdParams) (Phone, error)
	PhoneConfirmByNumberAndCountryCode(ctx context.Context, arg PhoneConfirmByNumberAndCountryCodeParams) (Phone, error)
	PhoneCreateOne(ctx context.Context, arg PhoneCreateOneParams) (Phone, error)
	PhoneDeleteById(ctx context.Context, id int64) (Phone, error)
	PhoneDeleteByNumberAndCountryCode(ctx context.Context, arg PhoneDeleteByNumberAndCountryCodeParams) (Phone, error)
	PhoneGetById(ctx context.Context, id int64) (Phone, error)
	PhoneGetByNumberAndCountryCode(ctx context.Context, arg PhoneGetByNumberAndCountryCodeParams) (Phone, error)
	UserCreateOne(ctx context.Context, arg UserCreateOneParams) (User, error)
	UserDeleteById(ctx context.Context, id int64) (User, error)
	UserGetById(ctx context.Context, id int64) (User, error)
	UserGetPreloadedById(ctx context.Context, id int64) (UserGetPreloadedByIdRow, error)
	UserSetAvatarUriById(ctx context.Context, arg UserSetAvatarUriByIdParams) (User, error)
	UserUpdateConfirmedById(ctx context.Context, arg UserUpdateConfirmedByIdParams) (User, error)
}

var _ Querier = (*Queries)(nil)
